#!/usr/bin/env bash
# This script prints a list of numbers from 1 - 100, but if the number is divisible by 3 and 5, it prints FizzBuzz, if 3, then Fizz, and if 5, then Buzz
for i in {1..100}; do
  if (( i % 3 == 0 )) && (( i % 5 == 0 )); then
    echo "FizzBuzz"
  elif (( i % 3 == 0 )); then
    echo "Fizz"
  elif (( i % 5 == 0 )); then
    echo "Buzz"
  else
    echo "$i"
  fi
done
