#!/usr/bin/env bash
# This script uses a while loop to read the contents of the /etc/passwd file
# line by line. It then assigns variables to each of the fields, and spits them
# in some weird grandma's trying to be a gangbanger story.
while IFS=: read -r user pass uid gid desc home shell; do
  echo "The user $user is part of the $gid gang, lives in $home and rides $shell. $uid's place is protected by the passcode $pass, more info about the user here: $desc"
done < /etc/passwd
