#!/usr/bin/env bash
# This script reads the apache-access.log file, pipes it into awk to print
# the first and 9th fields, the ip address and the HTTP error code
awk '{print $1 " " $9}' apache-access.log | sort | uniq -c | sort -nr
