#!/usr/bin/env bash
# This script echos "Best School" 10 times
hour=0
minute=0
while [ $hour -le 12 ]
do
	echo "Hour: $hour"
	((hour++))
	while [ $minute -le 60 ]
	do
		echo "$minute"
		((minute++))
	done
done
