#!/usr/bin/env bash
# This script checks to see if a file called school exists
FILE=school
if test -f "$FILE"; then
	echo "school file exists"

else
	echo "school file does not exist"
fi
if test -s "$FILE"; then
	echo "school file is not empty"
else
	echo "school file is empty"
fi
if test -d "$FILE"; then
	echo "school is a regular file"
fi
