#!/usr/bin/env bash
# a long script
echo $$ > /var/run/myscript.pid
while true
do
       echo "To infinity and beyond"
done
trap 'echo "I hate the kill command"' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm -f /var/run/myscript.pid' SIGQUIT SIGTERM
