#!/usr/bin/env bash
# a long script
function cleanup {
    echo "I hate the kill command"
    rm -f /var/run/myscript.pid
    exit 0
}

echo $$ > /var/run/myscript.pid

trap 'cleanup' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT

while true; do
    echo "To infinity and beyond"
    sleep 1
done
