#!/usr/bin/env bash
# This script uses pkill to kill any process with beyond in the name 
trap 'echo "I am invincible!!!"; exit 0' SIGTERM

while true; do
    echo "To infinity and beyond"
    sleep 2
done
